### ISSUE TITLE
error stop openLISEM version 6.95

### ISSUE THREAD

**Issue by fiiiiiia** [vjetten/openlisem#5]
I have managed to create the database with the lisem database generator, but I get an error message when I try to start the simulation. It tells me that the map "ksat1.map" has missing values. I have already tried several times and recreated the database several times for different study areas. What could be the problem?

**Comment by mcommelin** [comment]
Your ksat1.map probably has missing values inside the catchment area. If you use the [Nutshell](https://github.com/vjetten/NutShell/releases/tag/NutShell) program, you can view your maps. Does the ksat1.map has all missing values or just some spots?

**Comment by fiiiiiia** [comment]
It seems to have quite a lot missing values
![Screenshot 2024-05-07 162445](https://github.com/vjetten/openlisem/assets/163840774/5552a7c2-fb57-420f-a3e0-92cd35de3939)

**Comment by mcommelin** [comment]
Is this also the case for other maps produced by the database generator? In that case the data does not cover all parts of your catchment, and you will have to fill this yourself. On the wiki there is some information about creating the input maps without the generator: [preparing data](https://github.com/vjetten/openlisem/wiki/Prepare-Data) and a usefull PCRaster command: [lookup](https://github.com/vjetten/openlisem/wiki/Introduction-PCRaster-&-Nutshell#lookup).

**Comment by fiiiiiia** [comment]
It is also still the case for the "psi1.map". I think the other maps are fine. Then the missing values probably come from the soilgrids? I will try to create the maps myself. Thank you very much!
